name: Django CI

on:
  push:    #push할때마다 github action 돌아감

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codes
        uses: actions/checkout@v2

      - name: Setup python environment
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.9


      - name: Install dependencies
        run: |
           pip install -r requirements.txt --upgrade pip

      # black 추가
      - name: Run Black
        run: black . --check

      # isort 추가
      - name: Run Isort
        run: isort . --check --diff

      # test 실행
      - name: Run Tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
            python manage.py test

